server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyblue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 521521
  logging:
    level:
      com:
        cskaoyan:
          mapper: debug
          controller: info