server:
  port: 8080
pagehelper:
  helper-dialect: mysql
mybatis:
  type-handlers-package: com.cskaoyan.typehandler

logging:
    level:
      com:
        cskaoyan:
          mapper: debug
          controller: info
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  resources:
    static-locations: classpath:\META-INF\resources\,classpath:\resources\,classpath:\static\,classpath:\public\,file:D:\pic\

---
spring:
  profiles: Lai

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyblue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 521521
logging:
  level:
    com:
      cskaoyan:
        mapper: debug
pagehelper:
  helper-dialect: mysql #不要用dialect


---
spring:
  profiles: Jiang
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyblue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
---
spring:
  profiles: Yuan

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #prop:
#  upload-folder: D://pic//
#  url: http://localhost:8081/

---
spring:
  profiles: Chen
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyblue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
---
spring:
    profiles: Wang
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/skyblue?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1095920109
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
pagehelper:
  helper-dialect: mysql
---
spring:
  profiles: Fang
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 199420
logging:
  level:
    com:
      cskaoyan:
        mapper: debug
        controller: info



